### ISSUE TITLE
No ProgressCircular remover a prop de stroke e a substituir por uma que defina tamanhos pré-definidos, a fim de padronizar o uso

### ISSUE THREAD

**Issue by RafaelGondi** [Sysvale/cuida#162]
- No ProgressCircular remover a prop de stroke e a substituir por uma que defina tamanhos pré-definidos, a fim de padronizar o uso

![image](https://user-images.githubusercontent.com/20057968/111669099-33291600-87f5-11eb-832b-0f40c8f3daf6.png)

_Originally posted by @RafaelGondi in https://github.com/Sysvale/cuida/discussions/144#discussioncomment-499575_

- Aplicar definições de tamanho tanto no progressCircular quanto no UploadInput ao estilo vuetify (ter props small, large, etc)

**Comment by patriciacoelho** [comment]
Bota small, medium e large?

**Comment by RafaelGondi** [comment]
Boa small e large, o medium fica sendo o padrão
