### ISSUE TITLE
Estilos de item ativo estão sendo aplicados de forma duplicada

### ISSUE THREAD

**Issue by lucasn4s** [Sysvale/cuida#176]
No caso de haver mais de uma opção na NavBar com itens aninhados, ao selecionar algum deles, os estilos de item ativo são aplicados a todos os itens que contém subitens.

Exemplo:

![image](https://user-images.githubusercontent.com/17988272/119880159-56152c00-bf02-11eb-8ab6-db8f0c3f9b9b.png)

**Comment by RafaelGondi** [comment]
Fechado no pr #177
