### ISSUE TITLE
Adicionar execução dos testes ao CI do projeto

### ISSUE THREAD

**Issue by RafaelGondi** [Sysvale/cuida#243]
### Visão geral
Adicionar execução dos testes ao CI do projeto

### Propósito

- Em que cenário esse recurso vai ser utilizado?
No CI

- Como esse recurso ajuda a evoluir o Cuida?
Garantindo que todos os testes estão passando antes de um branch novo ser merjado no master

- Existem recursos no Cuida que são semelhantes, mas que não resolvem o problema?
Utilizávamos antes o Travis, mas após eles removerem o plano gratuito, precisamos encontrar outra solução, como o Github Actions

**Comment by lucasn4s** [comment]
Os testes já estão sendo executados automaticamente em PRs que estejam direcionados ao branch da versão 3.0, logo creio que esta issue pode ser fechada.
