### ISSUE TITLE
Bug nas bolinhas do componente Timeline

### ISSUE THREAD

**Issue by rodrigo-barboza** [Sysvale/cuida#272]
### Resumo do problema

No componente timeline, ao adicionar mais de um objeto as bolinhas ficam desalinhadas

![Print do problema](https://i.imgur.com/HHeL7BG.png)

Como mostra o print, esse desalinhamento ocorre do primeiro objeto para os posteriores.

### Detalhes técnicos

-   Versão do Cuida: 2.19.0
-   Navegador utilizado: chrome;
-   Versão do navegador: 101.0.4951.64;

**Comment by UendelC** [comment]
Ao investigar este problema, tive algumas conclusões:

- A linha de um evento possui a seguinte estilização:

```css
#timeline .event__row {
	display: flex;
	justify-content: space-between;
}
```

O que indica que elementos contidos na linha serão espaçados igualmente.

Como há várias linhas, qualquer mudança no tamanho em um dos campos do evento resultará no desalinhamento do pino central, isso é mais propício de acontecer no primeiro elemento `event.date`

Exemplos: 

![image](https://user-images.githubusercontent.com/21681869/183452986-fbd28b0e-0b18-4643-a45f-5a4d035e4c1d.png)

![image](https://user-images.githubusercontent.com/21681869/183453183-43630045-219a-48a0-9a77-917ffb98aec0.png)

![image](https://user-images.githubusercontent.com/21681869/183453288-63d93951-9a4f-4020-adec-b3dae384a030.png)

## Possíveis soluções

- Documentar que o campo event.date sempre seguirá a regra `00/00/0000` ou deverá sempre ter tamanho igual para todos os eventos.
- Dar um tamanho fixo ao campo event__date. o que pode quebrar o layout caso o usuário entre com muitos dados nesse campo.

**Comment by rodrigo-barboza** [comment]
Acredito que a melhor solução vai ser fixar o tamanho do date, mas talvez alguém tenha uma ideia melhor. Fiz uns testes aqui e isso resolve, mas como Uendel falou, se entrar com muitos dados no campo de date, pode quebrar o layout.

**Comment by RafaelGondi** [comment]
Resolvido na versão do componente do Cuida 3
