### ISSUE TITLE
Posicionamento do SideSheet

### ISSUE THREAD

**Issue by Gabrielr2508** [Sysvale/cuida#37]
Ao meu ver não faz sentido ter uma prop `left` e outra `right` já que elas são exclusivas. Deveria ser algo como a prop `position` dos outros componentes.

**Comment by geidsonc** [comment]
De fato a prop `position` deixa a lógica mais simples.

Pretendo contribuir com isso.

**Comment by geidsonc** [comment]
Fiz um rascunho da alteração.

Há alguma prentenção de continuar mantendo suporte ao `left` e `right`?

**Comment by geidsonc** [comment]
up

**Comment by RafaelGondi** [comment]
Acredito que não. O uso do position melhora a api do componente mesmo. Aprovei lá o/

**Comment by Gabrielr2508** [comment]
Fechando a issue já que o merge foi aceito.
