### ISSUE TITLE
Subtitle do StatusItem

### ISSUE THREAD

**Issue by Gabrielr2508** [Sysvale/cuida#38]
Não seria interessante usar um slot para o subtitle já que aceita html?

**Comment by Gabrielr2508** [comment]
Talvez os dois, usando a prop como fallback para caso o slot não seja fornecido

**Comment by lucasn4s** [comment]
Acho uma abordagem válida, inclusive que poderia ser adotada no texto do alerta. Vou trabalhar nessa alteração assim que tiver um tempo.
