### ISSUE TITLE
Componente de modal não está seguindo o padrão de documentação no Preview

### ISSUE THREAD

**Issue by hosanabarcelos** [Sysvale/cuida#386]
O template do componente na documentação, não está sendo renderizado. Com isso, não dá pra visualizar o code de exemplo do preview em "Mostrar código" .

**Comment by patriciacoelho** [comment]
Esse problema não ocorre no Cuida V3, como não damos mais suporte pra versão 2 acredito que não valha a pena fazer essa correção
