### ISSUE TITLE
Exemplo de código

### ISSUE THREAD

**Issue by gab0gomes** [Sysvale/cuida#39]
Não consigo ver o exemplo de código no https://sysvale.github.io/cuida. É proposital?

**Comment by Gabrielr2508** [comment]
Consigo alterar as props, mas não o markup...

**Comment by RafaelGondi** [comment]
Tá sem o exemplo de código por enquanto porque o exemplo que era mostrado era pouco relevante pelo modo como estão funcionando os stories em .mdx.

![photo_2020-10-08_18-05-19](https://user-images.githubusercontent.com/20057968/95513543-e4976600-0990-11eb-8403-dbcb20f40fa1.jpg)

No component-library, aquele preview foi construído por a gente. Acredito que podemos fazer algo semelhante, implementando o nosso, ou aguardar as próximas releases do storybook.
