### ISSUE TITLE
Implementar visualização semelhante ao addon "actions"

### ISSUE THREAD

**Issue by RafaelGondi** [Sysvale/cuida#45]
- Implementar visualização dos eventos em alguma parte da interface, com algo semelhante ao addon "actions"

**Comment by Gabrielr2508** [comment]
Eu até tentei, mas não entendi foi nada disso aqui. :(

**Comment by Gabrielr2508** [comment]
Ta bem diferente da documentação padrão as coisas, nem sei pra onde vai.

**Comment by RafaelGondi** [comment]
Tu fala com relação à estrutura do projeto ou a visualização em produção?

**Comment by Gabrielr2508** [comment]
Relação a tudo, estrutura de código e tals. Tentei fazer o setup do actions mas n funcionou.

Não sei pra onde vai no storybook.

**Comment by RafaelGondi** [comment]
Provavelmente não funcionou o actions pra ti porque estamos compilando o storybook no modo "docs" (no script tem um "--docs") e a galera do storybook não implementou a visualização das actions nesse modo ainda.

A ideia da issue era tentar contornar isso pra não termos que esperar pela implementação deles. Implementar no modo docs algum componente wrapper que fizesse aparecer um log ou algo assim.

**Comment by Gabrielr2508** [comment]
Porque ta compilando nesse modo?

**Comment by RafaelGondi** [comment]
No outro modo, os componentes ficam soltos na interface, sem documentação
