### ISSUE TITLE
Variantes de cor no Radio

### ISSUE THREAD

**Issue by hosanabarcelos** [Sysvale/cuida#470]
### Do que se trata o feature request?

- [ ] Novo componente
- [ ] Novo recurso na documentação
- [x] Novo recurso para facilitar o uso

### Visão geral

Seguindo os mockups, seria importante utilizar as variantes de cores no Radio, atualmente só temos a cor verde.

### Propósito

Facilitar o uso do Radio em aplicações onde a cor primária seja diferente da cor padrão do Cuida (Ex: O Minha vez tem como cor primária a cor indigo).

**Comment by patriciacoelho** [comment]
Esse recurso já foi implementado, encerrando a issue...
