### ISSUE TITLE
Caminhos relativos dentro dos componentes não são resolvidos pelo `npm run build`

### ISSUE THREAD

**Issue by patriciacoelho** [Sysvale/cuida#57]
Ao importar um componente ou imagem local usando caminho relativo apesar de o `npm run storybook` funcionar ao rodar o `npm run build` dá um problema pois não consegue resolver o caminho relativo e não consigo colocar um caminho absoluto dentro do componente

**Comment by RafaelGondi** [comment]
Acho que tu resolve isso colocando a importação e registro do componente no entry.js

**Comment by patriciacoelho** [comment]
Não sei, não lembro mais do contexto que essa issue surgiu para poder verificar, mas acho que esse registro deve resolver... Vou ver aqui as features desse período pra ver se lembro o contexto

**Comment by patriciacoelho** [comment]
Descobri que esse problema foi naquelas imagens do componente `UploadInput`

**Comment by RafaelGondi** [comment]
Entendi, no caso o problema não se resolve com o que eu falei mesmo. Vale a gente checar o que tá causando isso

**Comment by RafaelGondi** [comment]
Fechado em #56
